# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

# Site Settings
locale: "en-US"
title: "About Me"
title_separator: "|"
subtitle: "Data Scientist & Solution Architect"
name: "Bhaskar Kumar"
description: "Bhaskar Kumar's personal website and blog - Data Scientist, Solution Architect, and Flaneur"
url: "https://bprs68.github.io"
baseurl: ""
repository: "Bprs68/bprs68.github.io"
teaser: null
logo: null
masthead_title: "Bhaskar Kumar"
breadcrumbs: false
words_per_minute: 200

# Site Author - Removing avatar and keeping minimal info
author:
  name: "Bhaskar Kumar"
  bio: "Data Scientist | Solution Architect | Flaneur"
  location: "Mumbai, India"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Bprs68"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/bhaskar-kumar-"
    - label: "Medium"
      icon: "fab fa-fw fa-medium"
      url: "https://medium.com/@bhaskards6869"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:bhaskards6869@gmail.com"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Bprs68"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/bhaskar-kumar-"
    - label: "Medium"
      icon: "fab fa-fw fa-medium"
      url: "https://medium.com/@bhaskards6869"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
paginate: 10
paginate_path: /blog/page:num/
timezone: Asia/Kolkata

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/

# Defaults - Modified to remove images
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      show_date: true
      header:
        overlay_image: null
        teaser: null
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      header:
        overlay_image: null
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: false
      share: true
      header:
        overlay_image: null
        teaser: null
